const APP_NAME = 'R2R2R Training'

export function TermsPage() {
  return (
    <div className="legal-page">
      <h1>Terms and Conditions</h1>
      <p className="legal-updated">Last updated: July 19, 2026</p>

      <p>
        These Terms and Conditions ("Terms") govern your use of {APP_NAME} (the "Service"), a
        personal training application that provides training plans and text-message coaching for
        endurance events. By creating an account or using the Service, you agree to these Terms.
      </p>

      <h2>1. The Service</h2>
      <p>
        {APP_NAME} generates suggested training plans using automated systems, including artificial
        intelligence, based on information you provide and, if you connect it, your Strava activity
        data. The Service can send you text messages (SMS) with training suggestions, reminders,
        summaries, and conversational coaching, and you can reply to adjust your plan.
      </p>

      <h2>2. Not Medical or Professional Advice</h2>
      <p>
        The Service provides general fitness information generated by software. It is <strong>not
        medical advice</strong>, is not provided by a physician, licensed coach, or other
        professional, and is not a substitute for professional judgment. Consult a physician before
        beginning any training program, especially one involving strenuous endurance activity.
        Stop training and seek medical attention if you experience pain, dizziness, or other
        warning signs.
      </p>

      <h2>3. Assumption of Risk</h2>
      <p>
        Endurance training and events such as the Grand Canyon Rim to Rim to Rim involve inherent
        and significant risks, including serious injury, illness, and death, and depend on factors
        the Service cannot assess (terrain, weather, heat, altitude, your health on a given day).
        You are solely responsible for your training decisions, for evaluating your own fitness and
        conditions, and for your safety. You assume all risks associated with your training and any
        event you attempt. Automated suggestions may be wrong; use your own judgment.
      </p>

      <h2>4. Text Messaging Program</h2>
      <p>
        By providing your mobile number, you consent to receive recurring automated text messages
        from {APP_NAME}, including nightly training plans, post-workout messages, weekly summaries,
        and replies to messages you send. Message frequency varies (typically 1–3 messages per
        day). <strong>Message and data rates may apply.</strong> Consent is not a condition of any
        purchase.
      </p>
      <p>
        Reply <strong>STOP</strong> to cancel at any time; reply <strong>HELP</strong> for help.
        You can also change your phone number or delete your account in the app. Carriers are not
        liable for delayed or undelivered messages.
      </p>

      <h2>5. Your Account and Responsibilities</h2>
      <p>
        You agree to provide accurate information, to keep your contact details current, and to use
        the Service only for your own personal, non-commercial training. You must be at least 18
        years old. You are responsible for activity that occurs under your account.
      </p>

      <h2>6. Third-Party Services</h2>
      <p>
        The Service integrates with third parties, including Strava (activity data), Twilio
        (text messaging), and Anthropic (AI plan generation). Your use of Strava is governed by
        Strava's own terms; you may disconnect Strava from the Service at any time.
      </p>

      <h2>7. Disclaimer of Warranties</h2>
      <p>
        The Service is provided <strong>"as is" and "as available"</strong> without warranties of
        any kind, express or implied, including fitness for a particular purpose, accuracy, or
        availability. We do not warrant that plans are appropriate for you or that messages will be
        delivered on time or at all.
      </p>

      <h2>8. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, {APP_NAME} and its operator shall not be liable for
        any indirect, incidental, special, consequential, or punitive damages, or for any personal
        injury, arising out of or related to your use of the Service or your training activities.
        Where liability cannot be excluded, it is limited to the amount you paid for the Service in
        the twelve months before the claim (which may be zero).
      </p>

      <h2>9. Changes and Termination</h2>
      <p>
        We may modify or discontinue the Service, or update these Terms, at any time. Material
        changes will be reflected on this page with an updated date. Continued use after changes
        constitutes acceptance. You may stop using the Service and request deletion of your account
        at any time.
      </p>

      <h2>10. Contact</h2>
      <p>
        Questions about these Terms: contact the operator through the app or the contact
        information provided at registration.
      </p>

      <p><a href="#/">← Back to the app</a></p>
    </div>
  )
}

export function PrivacyPage() {
  return (
    <div className="legal-page">
      <h1>Privacy Statement</h1>
      <p className="legal-updated">Last updated: July 19, 2026</p>

      <p>
        This Privacy Statement explains what information {APP_NAME} (the "Service") collects, how
        it is used, and the choices you have.
      </p>

      <h2>1. Information We Collect</h2>
      <ul>
        <li>
          <strong>Profile information</strong> you provide: name, email address, mobile phone
          number, time zone, goal date, experience level, and weekly training availability.
        </li>
        <li>
          <strong>Strava activity data</strong>, only if you connect your Strava account: activity
          type, date, distance, elevation gain, duration, and average heart rate. We access this
          via Strava's API with your authorization and store the summary fields listed above.
        </li>
        <li>
          <strong>Text messages</strong>: the content of SMS messages you exchange with the
          Service, so the coaching assistant has conversation context.
        </li>
        <li>
          <strong>Training plan data</strong>: generated workouts, your edits, completion status,
          and constraints you report (for example injuries, fatigue, or travel).
        </li>
      </ul>

      <h2>2. How We Use Information</h2>
      <ul>
        <li>To generate and adapt your training plan.</li>
        <li>To send you the text messages described in the Terms (plans, summaries, replies).</li>
        <li>To show your calendar, progress, and adherence statistics in the app.</li>
        <li>To operate, debug, and improve the Service.</li>
      </ul>
      <p>We do <strong>not</strong> sell your personal information or use it for advertising.</p>

      <h2>3. Service Providers</h2>
      <p>Your information is shared only with the providers needed to run the Service:</p>
      <ul>
        <li>
          <strong>Twilio</strong> — to send and receive text messages (they process your phone
          number and message content).
        </li>
        <li>
          <strong>Anthropic</strong> — to generate plans and coaching replies (they process your
          profile summary, training load, plan, and conversation content sent to the AI model).
        </li>
        <li>
          <strong>Strava</strong> — when you connect it, we receive your activity data under your
          authorization; we do not write to your Strava account.
        </li>
        <li>
          <strong>Render</strong> — our hosting provider, where the application and its database
          run.
        </li>
      </ul>
      <p>
        <strong>SMS consent and phone numbers are not shared with third parties for their own
        marketing purposes.</strong>
      </p>

      <h2>4. Data Retention and Deletion</h2>
      <p>
        Your data is retained while your account is active so the Service can maintain your plan
        and history. You may delete your account at any time (or request deletion via the contact
        below), which removes your profile, plan, activities, messages, and Strava connection from
        our database. Disconnecting Strava stops further activity syncing; you can also revoke the
        Service's access from your Strava settings.
      </p>

      <h2>5. Security</h2>
      <p>
        Data is transmitted over HTTPS and stored on access-controlled infrastructure. Strava
        access tokens are stored server-side and never exposed to your browser. No method of
        transmission or storage is completely secure, and we cannot guarantee absolute security.
      </p>

      <h2>6. Children</h2>
      <p>The Service is not directed to children and is not intended for users under 18.</p>

      <h2>7. Changes</h2>
      <p>
        We may update this Privacy Statement from time to time; the date above reflects the latest
        revision. Material changes will be posted on this page.
      </p>

      <h2>8. Contact</h2>
      <p>
        Privacy questions or deletion requests: contact the operator through the app or the
        contact information provided at registration.
      </p>

      <p><a href="#/">← Back to the app</a></p>
    </div>
  )
}
